apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: result-app-pod
  template:
    metadata:
      name: reslut-app-pod
      labels:
        app: demo-voting-app
        name: result-app-pod

    spec:
      containers:
        -
          image: dockersamples/examplevotingapp_result
          name: result-app
          ports:
            -
              containerPort: 80
